// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/29/2026, 8:17:57 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/gharabawy/Pictures/elmarsam-website/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gharabawy/Pictures/elmarsam-website/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gharabawy/Pictures/elmarsam-website/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gharabawy/Pictures/elmarsam-website/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gharabawy/Pictures/elmarsam-website/app/plugins/**/*.{js,ts,mjs}","/home/gharabawy/Pictures/elmarsam-website/app/composables/**/*.{js,ts,mjs}","/home/gharabawy/Pictures/elmarsam-website/app/utils/**/*.{js,ts,mjs}","/home/gharabawy/Pictures/elmarsam-website/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gharabawy/Pictures/elmarsam-website/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/gharabawy/Pictures/elmarsam-website/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/gharabawy/Pictures/elmarsam-website/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;